version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    # Define the health check for the container
    healthcheck:
      # Use 'wget' to perform the health check within the container
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
